# Generated by Django 3.2 on 2021-04-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_itemstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemStatus',
            new_name='ItemState',
        ),
    ]
