# Generated by Django 3.2 on 2021-04-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_itemstatus_itemstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='date_created',
            new_name='date_raised',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='note',
            new_name='details',
        ),
        migrations.AddField(
            model_name='incident',
            name='linked_check',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
