# Generated by Django 3.2 on 2021-04-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210425_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='failure_details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
