# Generated by Django 3.2 on 2021-04-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_check_failure_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfCheck', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
