# Generated by Django 3.2 on 2021-04-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210426_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='check',
            name='tag_id',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
