# Generated by Django 3.2 on 2021-04-26 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210426_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.incident')),
                ('result_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.result')),
            ],
        ),
    ]
