# Generated by Django 3.2 on 2021-04-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_incident_resmapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='site_id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='team_id',
        ),
        migrations.AddField(
            model_name='check',
            name='site_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.site'),
        ),
        migrations.AddField(
            model_name='check',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.team'),
        ),
    ]
