# Generated by Django 3.2 on 2021-04-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_check_check_automation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='check_automation',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Email', 'Email'), ('Automated', 'Automated')], default='Manual', max_length=200, null=True),
        ),
    ]
