# Generated by Django 3.2 on 2021-04-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_result_incident_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='name',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='incident_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.incident'),
        ),
    ]
